---
title: "Comparing Model Implementations - Repetition"
author: "Khaled Fouda"
date: "`r Sys.Date()`"
output:
  html_document:
     df_print: paged 
     output_file: Documentation/html/Comapring_Model_Implementations_Tables.html
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=TRUE, echo=F, message=FALSE, warning=FALSE}
library(kableExtra)
library(magrittr)
library(tidyverse)
root_dir = "/mnt/campus/math/research/kfouda/main/HEC/Youssef/HEC_MAO_COOP/"
knitr::opts_knit$set(root.dir=root_dir)
knitr::opts_chunk$set(echo = FALSE, cache = FALSE, eval = TRUE, 
                      cache.path = paste0(root_dir,"/Documentation/cache/"))
#source("./Mao/SMC_functions6.R")
```


```{r echo=F, message=FALSE, warning=FALSE, include=F, eval=T}
source("./code_files/import_lib.R")
#path_to_data = "./saved_data/June18/"
library(data.table)
```


```{r include=FALSE, eval=FALSE, echo=FALSE}
# rmarkdown::render("Documentation/Rmd//4_Model_Comparison(1)_Tables.Rmd",
#                   output_dir = "Documentation/html/",
#                   output_file = "4_Model_Comparison_Tables_No_Covariate_Effects.html")
# 
# 
# rmarkdown::render("Documentation/Rmd//4_Model_Comparison(1)_Tables.Rmd",
                  # output_dir = "Documentation/html/")

```


### Model Summary
```{r}
load_data = function(note) {
   Models <- c(
   "SoftImpute",
   "Mao",
   #"CAMC_holdout",
   #"CAMC_kfold",
   "CASMC_rank_restriction",
   "CASMC_L2_regularization",
   "CASMC_one_iteration",
   #"CASMC_kfold",
   "Naive"
)
   file_list <- list.files(
      path = path_to_data,
      pattern =
         
         paste0(
            "((Compare_MC_Models_Youssef_Simulation_with_replications_",
            note, # [0-9]+.*
            ")|(Compare_MC_Models_Mao_Simulation_with_replications",
            note,
            "))\\.csv$"
         ),
      full.names = TRUE,
      recursive = F
   )
   
   results = data.frame()
   for (f in file_list)
      results = rbind(results, read.csv(f))
   
   results %<>%
      mutate(
         simulation = case_when(
            missinginess == 0 ~ "Mao",
            missinginess == 0.8 &
               collinearity == TRUE ~ "80% Missing with Coll",
            missinginess == 0.8 &
               collinearity == FALSE ~ "80% Missing",
            missinginess == 0.9 &
               collinearity == TRUE ~ "90% Missing with Coll",
            missinginess == 0.9 &
               collinearity == FALSE ~ "90% Missing"
         )
      )
   if(note == "")
      results$model = rep(Models, 5)
   return(results)
}
```

```{r}
Models <- c(
   "Mao",
   "SoftImpute",
   "CASMC-0",
   "CAMSC-1",
   "CASMC-2",
   "CASMC-3a",
   "CASMC-3b",
   "Naive"
)


Note <- c(
   "Mao's original model",
   "Soft-Impute (fit function from library and CV from Vignette)",
   "CASMC with Ridge on Beta",
   "CASMC with hard rank restriction on Beta",
   "CASMC with nuclear norm on Beta",
   "CASMC with Lasso on Beta (1-fold)",
   "CASMC with Lasso on Beta (10-fold)",
   "Missing values filled with row-column average and general linear regression applied"
)

model_rep <-
   c(
      "$\\begin{aligned} O = X \\beta + M  \\end{aligned}$",
      "$\\begin{aligned} O =  M  \\end{aligned}$",
      "$\\begin{aligned} O = X \\beta + AB^T  \\end{aligned}$",
      "$\\begin{aligned} O = X \\beta + AB^T  \\end{aligned}$",
      "$\\begin{aligned} O = P_{\\Omega}(O-X \\beta - AB^T) + (X \\beta + AB^T)\\\\ =Sparse +  Low Rank  \\end{aligned}$",
      "$\\begin{aligned} O = P_{\\Omega}(O-X \\beta - AB^T) + (X \\beta + AB^T)\\\\ =Sparse +  Low Rank\\end{aligned}$",
      ""
   )

hyperparameters <- c(
   "$(\\Theta,\\lambda_M, \\lambda_\\beta,\\alpha)$",
   "$(\\lambda_M,J)$",
   "$(\\lambda_\\beta, \\lambda_M, J)$",
   "$(\\lambda_M, r, J)$",
   "$(\\lambda_\\beta, r, \\lambda_M, J)$",
   "$(\\lambda_\\beta, \\lambda_M, J)$",
   "$(\\lambda_\\beta, \\lambda_M, J)$",
   ""
)

include_cov <- rep("Yes", 8)
include_cov[c(2)] <- "No"
Cross_validation_type <- rep("20% validation", 6, 8)
Cross_validation_type[c(1)] <- "5-folds"
Cross_validation_type[c(7)] <- "10-folds"
Cross_validation_type[c(8)] <- ""
Regular_cov <- rep("Ridge", 7)
Regular_cov[2] <- "None"
Regular_cov[4] <- "Hard Rank Constraint"
Regular_cov[5] <- "Nuclear"
Regular_cov[6:7] <- "Lasso"
Regular_cov[8] <- ""

data.frame(
   Model = Models,
   Note = Note,
   `Has Covariates?` = include_cov,
   `Cross-Validation Type` = Cross_validation_type,
   `Regularization on the Covariates?` = Regular_cov,
   #`New Model` = New_Model,
   #Model.Representation = model_rep,
   Hyperparameters = hyperparameters
) %>%
   kable("html",
         escape = FALSE,
         #align = 'c',
         caption = "Model Summary Table; $Y= P_{\\Omega}(O) + \\epsilon$ is observed where $\\Omega$ are the observed indices and $\\epsilon$ is a small random noise. (ie, Y is partially observed and slightly corrupted version of O.") %>%
   kable_styling(
      bootstrap_options = c("striped", "hover", "condensed"),
      full_width = F,
      position = "center"
   ) %>% 
   column_spec(2, width = "300px")

```






```{r eval=T, include=F}
# Function to color minimum values in green

# results <- results_MaoSim
#missingness=0; coll=FALSE;
print_table <-
   function(results,
           
            time = T) {

      
      nmodels = length(unique(results$model))
      names(results) = gsub("error\\.", "", names(results))
      
      
      combined_results <- results |> 
         rename(
            Method = model)
      
      combined_results %<>% 
         mutate(time_mean = ifelse(Method == "Naive", NA, time_mean),
                time_sd = ifelse(Method == "Naive", NA, time_sd))
      
      
      combined_results %<>%
         mutate_if(is.numeric, function(x)
            replace_na(as.character(round(x, 3)), ''))
      
      # Color the minimum errors for each pair of rows (200x200, 400x400, etc.)
      error_columns <- c("test", "corr.test", "train", "time", "lambda.M", "lambda.beta",
                         "rank_beta", "rank_M", "sparse_prop", "Prop_explained_xbeta",
                         "Prop_explained_M", "Prop_unexplained")
      
      for(ec in error_columns){
         combined_results[[ec]] <- paste0(combined_results[[paste0(ec,"_mean")]]," (",
                combined_results[[paste0(ec,"_sd")]], ")")
      }
      dim = ifelse(time, "[587x193]", "[193x587]")
      B = results$B[1]
      ncov = ifelse(time, "[#covariates=3]", "[#covariates=13]")
      miss_p = "[12% unobserved, 20% test, 20% validation]"
      
      
      tb_head = paste0("Dimension:",dim,"[#replications=",B,"]",miss_p, 
                       ncov)
      
      tb_head = paste0("<b style='font-size:20px'>",tb_head,"</b>")
      
      combined_results %>%
         dplyr::rename(seconds = time) %>% 
         select(Method,
            lambda.M,
            lambda.beta,
            corr.test,
            test,
            train,
            rank_beta,
            rank_M,
            sparse_prop,
            Prop_explained_xbeta,
            #Prop_explained_M,
            #Prop_unexplained,
            #rank_diff,
            seconds) %>%  
      rename(Proportion = sparse_prop,
             test_estimates = corr.test,
             McFadden = Prop_explained_xbeta,
             #explained_by_M = Prop_explained_M,
             #unexplained = Prop_unexplained
             ) |> 
         mutate_if(is.numeric, function(x)
            replace_na(as.character(round(x, 3)), '')) %>%
         mutate(across(everything(), ~ ifelse(.x=="NaN (NaN)","",.x))) |> 
         arrange(test) |> 
         kable("html",
               escape = FALSE,
               align = 'c',
               caption = tb_head) %>%
         kable_styling(
            bootstrap_options = c("striped", "hover", "condensed"),
            full_width = F,
            position = "center"
         ) %>%
         add_header_above(c(
            "Fixed" = 1,
            "Hyperparameters" = 2,
            "Correlation" = 1,
            "Error on" = 2,
            "Rank" = 2,
            "Sparsity" = 1,
            "Pseudo Rsquared" = 1,
            "Time" = 1
         )) %>%
         column_spec(
            4,
            bold = T,
            background = grDevices::adjustcolor("pink", alpha.f = 0.1)
         ) 
   }
```



## Using Time Covariates

```{r fig.height=15, fig.width=15, results='asis', eval=T, echo=F}
read_csv("BIXI/results/Model_results_.csv", 
                    show_col_types = F) |> 
   print_table(time = T)
```



## Using Station Covariates

```{r fig.height=15, fig.width=15, results='asis', eval=T, echo=F}
read_csv("BIXI/results/station_Model_results_.csv", 
                    show_col_types = F) |> 
   print_table(time = F)
```




#---------------------------------------

## Time Covariates' Effects 

```{r fig.height=15, fig.width=15, results='asis', eval=T, echo=F}

means <- read.csv("BIXI/results/cov_means.csv") |> 
 filter(Model != "SoftImpute" & Model != "Naive")
sds <- read.csv("BIXI/results/cov_std.csv") |> 
 filter(Model != "SoftImpute" & Model != "Naive")

sds <- sds %>%
  rename_with(~ gsub("^", "", .x), everything())

combined <- means %>%
  inner_join(sds, by = c("Model", "Variable"), suffix = c("_mean", "_sd"))

combined <- combined %>%
  mutate(across(matches("_mean$"), 
                ~ paste0(round(.x, 3), " (", round(get(sub("_mean$", "_sd", cur_column())), 3), ")"),
                .names = "{sub('_mean$', '', .col)}")) %>%
  select( Variable, Min, X1st_Qu, Median, Mean, X3rd_Qu, Max, prop_non_zero)


combined <- combined %>%
  mutate(Variable = case_when(
    Variable == "humidity" ~ cell_spec(Variable, color = "green"),
    Variable == "max_temp_f" ~ cell_spec(Variable, color = "blue"),
    Variable == "holiday" ~ cell_spec(Variable, color = "red"),
    TRUE ~ Variable
  ))

combined %>%
  kable("html", escape = FALSE, align = 'c', caption = "Summary of Means and Standard Deviations") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "center") %>%
  
  row_spec(0, bold = TRUE) %>% 
  pack_rows("Mao", 1, 3, hline_after = TRUE) %>%
  pack_rows("CASMC-0_Ridge", 4, 6, hline_after = TRUE) %>%
  pack_rows("CASMC-1_Hard_Rank", 7, 9, hline_after = TRUE) %>%
  pack_rows("CASMC-2_Nuclear", 10, 12, hline_after = TRUE) %>%
  pack_rows("CASMC-3a_Lasso_single_split", 13, 15, hline_after = TRUE)
```


# Station Covariates' Effects


```{r fig.height=15, fig.width=15, results='asis', eval=T, echo=F}

means <- read.csv("BIXI/results/station_cov_means.csv") |> 
  filter(Model != "SoftImpute" & Model != "Naive")
sds <- read.csv("BIXI/results/station_cov_std.csv") |> 
  filter(Model != "SoftImpute" & Model != "Naive")

sds <- sds %>%
  rename_with(~ gsub("^", "", .x), everything())

combined <- means %>%
  inner_join(sds, by = c("Model", "Variable"), suffix = c("_mean", "_sd"))

combined <- combined %>%
  mutate(across(matches("_mean$"), 
                ~ paste0(round(.x, 3), " (", round(get(sub("_mean$", "_sd", cur_column())), 3), ")"),
                .names = "{sub('_mean$', '', .col)}")) %>%
  select(Variable, Min, X1st_Qu, Median, Mean, X3rd_Qu, Max, prop_non_zero)

combined <- combined %>%
  mutate(Variable = case_when(
    Variable == "walkscore" ~ cell_spec(Variable, color = "green"),
    Variable == "len_minor_road" ~ cell_spec(Variable, color = "blue"),
    Variable == "num_restaurants" ~ cell_spec(Variable, color = "red"),
    Variable == "capacity" ~ cell_spec(Variable, color = "purple"),
    Variable == "area_park" ~ cell_spec(Variable, color = "orange"),
    Variable == "len_major_road" ~ cell_spec(Variable, color = "cyan"),
    Variable == "num_other_commercial" ~ cell_spec(Variable, color = "magenta"),
    Variable == "num_bus_stations" ~ cell_spec(Variable, color = "brown"),
    Variable == "num_pop" ~ cell_spec(Variable, color = "pink"),
    Variable == "num_university" ~ cell_spec(Variable, color = "yellow"),
    Variable == "num_metro_stations" ~ cell_spec(Variable, color = "grey"),
    Variable == "num_bus_routes" ~ cell_spec(Variable, color = "darkgreen"),
    Variable == "len_cycle_path" ~ cell_spec(Variable, color = "darkblue"),
    TRUE ~ Variable
  ))

combined %>%
  kable("html", escape = FALSE, align = 'c', caption = "Summary of Means and Standard Deviations for New Variables") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "center") %>%
  row_spec(0, bold = TRUE) %>%
   pack_rows("Mao", 1, 13, hline_after = TRUE) %>%
  pack_rows("CASMC-0_Ridge", 14, 26, hline_after = TRUE) %>%
  pack_rows("CASMC-1_Hard_Rank", 27, 39, hline_after = TRUE) %>%
  pack_rows("CASMC-2_Nuclear", 40, 52, hline_after = TRUE) %>%
  pack_rows("CASMC-3a_Lasso_single_split", 53, 65, hline_after = TRUE)

```
