---
title: "July 10th -BIXI Analysis notes - Station Covariates - see Obsidian"
author: "Khaled Fouda"
date: ""
output:
  html_document:
     df_print: paged 
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=TRUE, echo=T, message=FALSE, warning=FALSE}
library(kableExtra)
library(magrittr)
library(tidyverse)
root_dir = "/mnt/campus/math/research/kfouda/main/HEC/Youssef/HEC_MAO_COOP/"
knitr::opts_knit$set(root.dir=root_dir)
knitr::opts_chunk$set(echo = T, cache = FALSE, eval = TRUE, 
                      fig.width=12, fig.height=8,
                      cache.path = paste0(root_dir,"/Documentation/cache/"))
```


```{r echo=F, message=FALSE, warning=FALSE, include=F, eval=T}
source("./code_files/import_lib.R")
source("./BIXI/data/transform_data_into_mat.R")
source("./BIXI/model_comparison/fit_wrappers_bixi2.R")
model_functions = list(
      SImpute_Bixi_Wrapper,
      CAMC_0_Bixi_Wrapper,
      CAMC_2_Bixi_Wrapper,
      CAMC_3a_Bixi_Wrapper,
      Mao_Bixi_Wrapper,
      Naive_Bixi_Wrapper
   )

model_names <- list(
 "SoftImpute",
 "CAMC-Ridge",
 "CAMC-Nuclear",
 "CAMC-Lasso",
 "Mao",
 "Naive LM"
)

```


## Fit all models

```{r}

model.dat <-  dat <- load_model_bixi_dat(time_cov = FALSE)
dat$splits$test[dat$masks$test==0] 



results <-  SImpute_Bixi_Wrapper(model.dat)
loglik_SI <- results$LogLik
results <- as.data.frame(results$results)
data.frame() -> covsum 
results$cov_summaries <- NULL

model_fits <- list()

for(i in 2:length(model_functions)){
 hpar = NULL
  print(model_names[[i]])
  if(i == 2){
    hpar = CAMC_Ridge_hparams
    hpar$beta$n.lambda = 40
  }else if(i == 3){
    hpar = CAMC_Nuclear_hparams
    hpar$beta$lambda.factor = 1
    hpar$beta$n.lambda = 60
  }else if(i == 4){
    hpar = CAMC_Lasso_hparams
    hpar$beta$lambda.max = .5
    hpar$beta$n.lambda = 40  
  }
  
 out <- model_functions[[i]](model.dat, train_on_all = TRUE, LogLik_SI = loglik_SI,
                             return_fit = TRUE, hpar = hpar)
 if(i %in% 3:5){
  model_fits[[i-2]] <- out$fit
  out <- out$results
 }
 covsum %<>%
  rbind(
   out$cov_summaries %>% 
   mutate(model = model_names[[i]])
  )
 out$cov_summaries <- NULL
 out$model <- model_names[[i]]
 results %<>% rbind(as.data.frame(out))
}

```


## load BKTR fit data

```{r}


bktr.fit <- readRDS("./BIXI/data/fits/split_1_fit.rds")
train.df <- readRDS(paste0("./BIXI/data/splits/split_1_train.rds"))
test.df <-  readRDS(paste0("./BIXI/data/splits/split_1_test.rds"))

bktr.fit$imputed_y_estimates |> 
  as.data.frame() |> 
  merge(test.df, by = c("location", "time")) |> 
  select(location, time, y_est, nb_departure) -> 
  test.estimates

bktr.fit$imputed_y_estimates |> 
  as.data.frame() |> 
  merge(filter(train.df, ! is.na(nb_departure)), by = c("location", "time")) |> 
  select(location, time, y_est, nb_departure) -> 
  train.estimates


results %<>% 
 rbind(
  
prepare_output_bixi(Sys.time(), dat$X, test.estimates$y_est,
                    train.estimates$y_est, test.estimates$nb_departure,
                    train.estimates$nb_departure) %>% 
 as.data.frame() %>% 
 mutate(cov_summaries = NULL, model = "BKTR",
        lambda.beta = NA, lambda.M = NA)
 )



covsum %<>% 
 rbind(
bktr.fit$beta_estimates %>% 
 as.data.frame() %>% 
 select(-location, -time, -Intercept) %>% 
 apply(2, summary) %>% 
 t() %>% 
 as.data.frame() %>% 
 mutate(prop_non_zero = 1, model = "BKTR")
 )


```




## Present Results table


```{r}
results %>% 
 arrange(desc(corr.test)) |> 
 mutate_if(is.numeric, function(x) round(x,4)) |> 
 kable()


```

## covariate Summaries



```{r}
bktr.fit$beta_covariates_summary 


error_metric$rmse(test.estimates$y_est, test.estimates$nb_departure) |> print()
error_metric$mae(test.estimates$y_est, test.estimates$nb_departure) |>  print()
error_metric$spearman(test.estimates$y_est, test.estimates$nb_departure) |>  print()


```


```{r}

# covsum <- covsum %>%
#   arrange(model)
nx <- ncol(dat$X)
# Create the table using kable and kableExtra
covsum %>%
 filter(! model %in% c("Mao", "Naive LM") ) %>% 
  kable("html", col.names = c("Min", "1st Qu.", "Median", "Mean", "3rd Qu.", "Max", "Prop Non Zero", "Model"),
        caption = "Covariate Summaries by Model") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "center") %>%
  row_spec(0, bold = TRUE) %>%
  # pack_rows("Mao", 1, 3, hline_after = TRUE) %>%
  pack_rows("CAMC-Ridge", 1, nx, hline_after = TRUE) %>%
  pack_rows("CAMC-Nuclear", nx+1, 2 * nx , hline_after = TRUE) %>%
  pack_rows("CAMC-Lasso", (2*nx)+1, 3*nx, hline_after = TRUE) %>%  
  pack_rows("BKTR", 3*nx + 1, 4 * nx, hline_after = TRUE)

```


## Plot: time vs average beta value  x4 models


```{r}

model_fits[[1]]$beta %>% t() %>% as.data.frame() %>% 
  `colnames<-`(colnames(dat$X)) %>% 
  mutate(model = model_names[[3]]) %>% 
  rbind(
    model_fits[[2]]$beta %>% t() %>% as.data.frame() %>% 
      `colnames<-`(colnames(dat$X)) %>% 
      mutate(model = model_names[[4]])
  ) %>%
  rbind(
    model_fits[[3]]$beta %>% t() %>% as.data.frame() %>% 
      `colnames<-`(colnames(dat$X)) %>% 
      mutate(model = model_names[[5]])
  ) %>% 
  rbind(
    bktr.fit$beta_estimates %>% as.data.frame() %>% 
      arrange(location, time) %>% 
      group_by(time) %>% 
      summarise(time = time[1], 
                walkscore = mean(walkscore),
                capacity = mean(capacity),
                num_metro_stations = mean(num_metro_stations),
                num_bus_routes = mean(num_bus_routes),
                num_university = mean(num_university),
                len_minor_road = mean(len_minor_road),
                num_pop = mean(num_pop),
                area_park = mean(area_park)) %>% 
      ungroup() %>% 
      select(-time) %>% 
      mutate(model = "BKTR")  
  ) %>%
  pivot_longer(
    cols = c(walkscore, capacity, num_metro_stations, num_bus_routes, num_university, len_minor_road, num_pop, area_park), 
    names_to = "covariate", values_to = "value"
  ) %>% 
  group_by(model, covariate) %>% 
  mutate(station_id =  1:ncol(dat$Y)) %>% 
  ungroup() ->
  df_long

 plot_model <- function(model_name) {
  df_long %>% filter(model == model_name) %>% 
  ggplot(aes(x = station_id, y = value, color = covariate, group = covariate)) +
    geom_point() +
    #geom_ribbon(aes(ymin = value - 0.1, ymax = value + 0.1), alpha = 0.2) + # Adjust ymin and ymax based on your data
    facet_wrap(~ covariate, scales = "free_y") +
    theme_minimal() +
    ggtitle(model_name) +
    theme(plot.title = element_text(hjust = 0.5),
          legend.position = "none")
}
 
p1 <- plot_model("CAMC-Ridge")
p2 <- plot_model("CAMC-Nuclear")
p3 <- plot_model("CAMC-Lasso")
p4 <- plot_model("BKTR")

gridExtra::grid.arrange(p1, p2, p3, p4, ncol = 2, nrow = 2)



```


## Plot: observed Y vs estimated Y. x4/5 models

```{r}
ms <- model_fits[[1]]

data.frame(True = dat$splits$test[dat$masks$test==0],
           Predicted =  model_fits[[1]]$estimates[dat$masks$test==0],
           model = model_names[[3]]) %>%
 rbind(
  data.frame(True = dat$splits$test[dat$masks$test==0],
           Predicted =  model_fits[[2]]$estimates[dat$masks$test==0],
           model = model_names[[4]])
 ) %>% 
 rbind(
  data.frame(True = dat$splits$test[dat$masks$test==0],
           Predicted =  model_fits[[3]]$estimates[dat$masks$test==0],
           model = model_names[[5]])
 ) %>% 
 rbind(
 transmute(test.estimates,  True = nb_departure,
           Predicted = y_est,
           model = "BKTR") 
 ) %>%  
 group_by(model) %>% 
 mutate(id =  1:length(model.dat$splits$test@x)) %>% 
 ungroup() ->
 df_long


plot_true_vs_predicted <- function(model_name) {
  ggplot(df_long %>% filter(model == model_name), aes(x = True, y = Predicted)) +
    geom_point(color = "black", size = 1, alpha = 0.6) +
    geom_abline(intercept = 0, slope = 1, #linetype = "dashed", 
                color = "blue",linewidth=1.1) + 
    theme_minimal(base_size = 15) +
    ggtitle(model_name) +
    theme(plot.title = element_text(hjust = 0.5, size = 18, face = "bold"),
          axis.title = element_text(size = 14),
          axis.text = element_text(size = 12)) +
    labs(x = "True Values", y = "Predicted Values") +
    theme(legend.position = "none") +
   # scale_y_continuous(expand = c(0, 0)) +
   # scale_x_continuous(expand = c(0, 0)) +
   xlim(0,1) +
   ylim(min(df_long$Predicted), max(df_long$Predicted))
     
}

p1 <- plot_true_vs_predicted("CAMC-Ridge")
p2 <- plot_true_vs_predicted("CAMC-Nuclear")
p3 <- plot_true_vs_predicted("CAMC-Lasso")
p4 <- plot_true_vs_predicted("BKTR")

gridExtra::grid.arrange(p1, p2, p3, p4, ncol = 2, nrow = 2)


```


##  Check Residuals


### CAMC-Ridge

```{r}
Residuals <- dat$splits$test[dat$masks$test==0] - 
            model_fits[[1]]$estimates[model.dat$masks$test==0]  
residual_analysis(Residuals) 
```

### CAMC-Nuclear

```{r}
Residuals <- dat$splits$test[dat$masks$test==0] - 
            model_fits[[2]]$estimates[model.dat$masks$test==0]  
residual_analysis(Residuals) 
```


### CAMC-Lasso

```{r}
Residuals <- dat$splits$test[dat$masks$test==0] - 
            model_fits[[3]]$estimates[model.dat$masks$test==0]  
residual_analysis(Residuals) 
```

### BKTR

```{r}
Residuals <- test.estimates$nb_departure - test.estimates$y_est  
residual_analysis(Residuals) 
```



## Something about covariates?
