---
title: "Comparing Model Implementations - Repetition"
author: "Khaled Fouda"
date: "`r Sys.Date()`"
output:
  html_document:
     df_print: paged 
     output_file: Documentation/html/Comapring_Model_Implementations_Tables.html
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=TRUE, echo=F, message=FALSE, warning=FALSE}
library(kableExtra)
library(magrittr)
library(tidyverse)
root_dir = "/mnt/campus/math/research/kfouda/main/HEC/Youssef/HEC_MAO_COOP/"
knitr::opts_knit$set(root.dir=root_dir)
knitr::opts_chunk$set(echo = FALSE, cache = FALSE, eval = TRUE, 
                      cache.path = paste0(root_dir,"/Documentation/cache/"))
#source("./Mao/SMC_functions6.R")
```


```{r echo=F, message=FALSE, warning=FALSE, include=F, eval=T}
source("./code_files/import_lib.R")
path_to_data = "./saved_data/July05/"
library(data.table)
```


```{r include=FALSE, eval=FALSE, echo=FALSE}
# rmarkdown::render("Documentation/Rmd//4_Model_Comparison(1)_Tables.Rmd",
#                   output_dir = "Documentation/html/",
#                   output_file = "4_Model_Comparison_Tables_No_Covariate_Effects.html")
# 
# 
# rmarkdown::render("Documentation/Rmd//4_Model_Comparison(1)_Tables.Rmd",
                  # output_dir = "Documentation/html/")

```


### Model Summary
```{r}
load_data = function(note) {
   Models <- c(
   "SoftImpute",
   "Mao",
   #"CAMC_holdout",
   #"CAMC_kfold",
   "CASMC_rank_restriction",
   "CASMC_L2_regularization",
   "CASMC_one_iteration",
   #"CASMC_kfold",
   "Naive"
)
   file_list <- list.files(
      path = path_to_data,
      pattern =
         
         paste0(
            "((Compare_MC_Models_Youssef_Simulation_with_replications_",
            note, # [0-9]+.*
            ")|(Compare_MC_Models_Mao_Simulation_with_replications",
            note,
            "))\\.csv$"
         ),
      full.names = TRUE,
      recursive = F
   )
   
   results = data.frame()
   for (f in file_list)
      results = rbind(results, read.csv(f))
   
   results %<>%
      mutate(
         simulation = case_when(
            missinginess == 0 ~ "Mao",
            missinginess == 0.8 &
               collinearity == TRUE ~ "80% Missing with Coll",
            missinginess == 0.8 &
               collinearity == FALSE ~ "80% Missing",
            missinginess == 0.9 &
               collinearity == TRUE ~ "90% Missing with Coll",
            missinginess == 0.9 &
               collinearity == FALSE ~ "90% Missing"
         )
      )
   if(note == "")
      results$model = rep(Models, 5)
   return(results)
}
```

```{r}
Models <- c(
   "Mao",
   "SoftImpute",
   "CASMC-0",
   "CAMSC-1",
   "CASMC-2",
   "CASMC-3a",
   "CASMC-3b",
   "Naive"
)


Note <- c(
   "Mao's original model",
   "Soft-Impute (fit function from library and CV from Vignette)",
   "CASMC with Ridge on Beta",
   "CASMC with hard rank restriction on Beta",
   "CASMC with nuclear norm on Beta",
   "CASMC with Lasso on Beta (1-fold)",
   "CASMC with Lasso on Beta (10-fold)",
   "Missing values filled with row-column average and general linear regression applied"
)

model_rep <-
   c(
      "$\\begin{aligned} O = X \\beta + M  \\end{aligned}$",
      "$\\begin{aligned} O =  M  \\end{aligned}$",
      "$\\begin{aligned} O = X \\beta + AB^T  \\end{aligned}$",
      "$\\begin{aligned} O = X \\beta + AB^T  \\end{aligned}$",
      "$\\begin{aligned} O = P_{\\Omega}(O-X \\beta - AB^T) + (X \\beta + AB^T)\\\\ =Sparse +  Low Rank  \\end{aligned}$",
      "$\\begin{aligned} O = P_{\\Omega}(O-X \\beta - AB^T) + (X \\beta + AB^T)\\\\ =Sparse +  Low Rank\\end{aligned}$",
      ""
   )

hyperparameters <- c(
   "$(\\Theta,\\lambda_M, \\lambda_\\beta,\\alpha)$",
   "$(\\lambda_M,J)$",
   "$(\\lambda_\\beta, \\lambda_M, J)$",
   "$(\\lambda_M, r, J)$",
   "$(\\lambda_\\beta, r, \\lambda_M, J)$",
   "$(\\lambda_\\beta, \\lambda_M, J)$",
   "$(\\lambda_\\beta, \\lambda_M, J)$",
   ""
)

include_cov <- rep("Yes", 8)
include_cov[c(2)] <- "No"
Cross_validation_type <- rep("20% validation", 6, 8)
Cross_validation_type[c(1)] <- "5-folds"
Cross_validation_type[c(7)] <- "10-folds"
Cross_validation_type[c(8)] <- ""
Regular_cov <- rep("Ridge", 7)
Regular_cov[2] <- "None"
Regular_cov[4] <- "Hard Rank Constraint"
Regular_cov[5] <- "Nuclear"
Regular_cov[6:7] <- "Lasso"
Regular_cov[8] <- ""

data.frame(
   Model = Models,
   Note = Note,
   `Has Covariates?` = include_cov,
   `Cross-Validation Type` = Cross_validation_type,
   `Regularization on the Covariates?` = Regular_cov,
   #`New Model` = New_Model,
   #Model.Representation = model_rep,
   Hyperparameters = hyperparameters
) %>%
   kable("html",
         escape = FALSE,
         #align = 'c',
         caption = "Model Summary Table; $Y= P_{\\Omega}(O) + \\epsilon$ is observed where $\\Omega$ are the observed indices and $\\epsilon$ is a small random noise. (ie, Y is partially observed and slightly corrupted version of O.") %>%
   kable_styling(
      bootstrap_options = c("striped", "hover", "condensed"),
      full_width = F,
      position = "center"
   ) %>% 
   column_spec(2, width = "300px")

```






```{r eval=T, include=F}
# Function to color minimum values in green

# results <- results_MaoSim
#missingness=0; coll=FALSE;
print_table <-
   function(results,
            #missingness = NULL,
            #coll = TRUE,
            #prob = NA,
            caption = "") {
      #$$
      
      
      nmodels = length(unique(results$model))
      names(results) = gsub("error\\.", "", names(results))
      
      # results %>%
      #    filter(missinginess == missingness, collinearity == coll) %>%
      #    dplyr::rename(
      #       O_mean = all_mean,
      #       O_sd = all_sd,
      #       O_test_mean = test_mean,
      #       O_test_sd = test_sd,
      #       Method = model,
      #       missing_prob = missinginess
      #    ) %>%
      #    mutate(rank_diff = rank_mean - true_rank) %>%
      #    select(
      #       Method,
      #       true_rank,
      #       missing_prob,
      #       rank_diff,
      #       contains("_mean"),
      #       contains("_sd"),
      #       -contains("alpha")
      #       # lambda.1,
      #       # lambda.2,
      #       # O_test,
      #       # O,
      #       # M,
      #       # Beta,
      #       # rank,
      #       # seconds
      #    )   -> combined_results
      # 
      combined_results <- results |> 
         rename(O_train_mean = train_mean,
            O_train_sd = train_sd,
            O_test_mean = test_mean,
            O_test_sd = test_sd,
            Method = model,
            missing_prob = missinginess)
      
      combined_results %<>% 
         mutate(time_mean = ifelse(Method == "Naive", NA, time_mean),
                time_sd = ifelse(Method == "Naive", NA, time_sd))
      
      #$$
      # test_col = 6
      # if (missingness == 0) {
      #    test_col = 6
      #    #combined_results$missing_prob = 0.8 #%<>% select(-missing_prob)
      #    nfixed = 2
      # } else
      #    nfixed = 2
      
      
      combined_results %<>%
         mutate_if(is.numeric, function(x)
            replace_na(as.character(round(x, 3)), ''))
      
      # error_columns <- c("O_test", "O", "beta", "M", "time", "lambda.M", "lambda.beta",
      #                    "rank_beta", "rank_M", "sparse_in_sparse", "sparse_in_nonsparse")
      # 
      sapply(names(select(combined_results, contains("mean"))),
             function(x)str_split(x,"_mean")[[1]][1] )  |> as.vector() ->
         error_columns
      
      for(ec in error_columns){
         combined_results[[ec]] <- paste0(combined_results[[paste0(ec,"_mean")]]," (",
                combined_results[[paste0(ec,"_sd")]], ")")
      }
      dim = results$dim[1]
      B = results$B[1]
      #sim_type = "Sim-C"
      ncov = paste0("[#covariates=",results$k[1],"]")
      rank_r = paste0("[Rank of M",results$rank_r[1],"]")
      mar_beta = ifelse(results$mar_beta[1], "[MAR in beta]", "[missing-by-row in beta]")
      mar_beta = ifelse(results$inform_prop[1]==1, "", mar_beta)
      half_disc = ifelse(results$half_disc[1], "[half of covariates are discrete]", "")
      informs = paste0("[ percent of informative covariates is: ",round(results$inform_prop[1]*100),"%]")
      coll_type = ifelse(results$collinearity[1]==TRUE, "[w/collinearity]", "")
      miss_p = ifelse(results$missinginess[1]==0, "[80% missing] ",
                      paste0("[", as.integer(results$missinginess[1]*100),"% missing] "  ))
      
      
      tb_head = paste0("Dimension:",dim,"[#replications=",B,"]",miss_p, coll_type,
                       ncov, rank_r, informs, mar_beta, half_disc)
      
      tb_head = paste0("<b style='font-size:20px'>",tb_head,"</b>")
      
      combined_results %>%
         dplyr::rename(seconds = time) %>% 
         select(Method,
            lambda.beta,
            lambda.M,
            corr.test,
            O_test,
            O_train,
            beta,
            M,
            rank_beta,
            rank_M,
            sparse_in_sparse,
            nonsparse_in_nonsparse,
            likelihood_ratio_index,
            Cox_Snell_R2,
            #rank_diff,
            seconds) %>% 
      rename(in_sparse = sparse_in_sparse,
             in_nonsparse = nonsparse_in_nonsparse) |> 
         mutate_if(is.numeric, function(x)
            replace_na(as.character(round(x, 3)), '')) %>%
         mutate(across(everything(), ~ ifelse(.x=="NaN (NaN)","",.x))) |> 
         arrange(desc(corr.test)) |> 
         kable("html",
               escape = FALSE,
               align = 'c',
               caption = tb_head) %>%
         kable_styling(
            bootstrap_options = c("striped", "hover", "condensed"),
            full_width = F,
            position = "center"
         ) %>%
         add_header_above(c(
            "Fixed" = 1,
            "Hyperparameters" = 2,
            "Error on" = 5,
            "Rank" = 2,
            "Sparse" = 1,
            "Dense" = 1,
            "Pseudo R2" = 2,
            "Time" = 1
         )) %>%
         column_spec(
            4:5,
            bold = T,
            background = grDevices::adjustcolor("pink", alpha.f = 0.1)
         ) 
   }
```



```{r, include=FALSE, eval=FALSE}
res1 <- load_data("_new_90_coll_FALSE_dim_400x500") |>
   rbind(load_data("_new_90_coll_FALSE_dim_700x800")) |>
   rbind(load_data("_new18_90_coll_FALSE_dim_700x800")) |> 
   rbind(load_data("_new25_90_coll_FALSE_dim_700x800")) |> 
   rbind(load_data("_new47_90_coll_FALSE_dim_700x800"))

res1 <- 



res1 |> 
   group_by(dim, model) |> 
   summarise(
    across(ends_with("_mean") | ends_with("_sd"), ~mean(.x,na.rm=T), .names = "{col}"),
    B = sum(B),
    across(!ends_with("_mean") & !ends_with("_sd") & !matches("^B$"), first, .names = "{col}")
  ) |> 
   ungroup() |> 
   as.data.frame() ->
   res1
   

res1

```



```{r fig.height=15, fig.width=15, results='asis', eval=T, echo=F}
read_csv("saved_data/July05/Model_Comparison_simulation_replications__1_.csv", show_col_types = F) |> 
   print_table(caption = "Case 1")
```


```{r fig.height=15, fig.width=15, results='asis', eval=T, echo=F}
read_csv("saved_data/July05/Model_Comparison_simulation_replications__2_.csv", show_col_types = F) |> 
   print_table(caption = "Case 2")
```



```{r fig.height=15, fig.width=15, results='asis', eval=T, echo=F}
read_csv("saved_data/July05/Model_Comparison_simulation_replications__3_.csv", show_col_types = F) |> 
   print_table(caption = "Case 3")
```



```{r fig.height=15, fig.width=15, results='asis', eval=T, echo=F}
read_csv("saved_data/July05/Model_Comparison_simulation_replications__4_.csv", show_col_types = F) |> 
   print_table(caption = "Case 4")
```



```{r fig.height=15, fig.width=15, results='asis', eval=T, echo=F}
read_csv("saved_data/July05/Model_Comparison_simulation_replications__5_.csv", show_col_types = F) |> 
   print_table(caption = "Case 5")
```

