---
title: "Comparing Model Implementations - Reproducing Table 1 in Mao's Paper"
author: "Khaled Fouda"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=TRUE, echo=F, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = F, cache = FALSE)
library(kableExtra)
library(magrittr)
library(tidyverse)
knitr::opts_knit$set(root.dir="/mnt/campus/math/research/kfouda/main/HEC/Youssef/HEC_MAO_COOP/")
#source("./Mao/SMC_functions6.R")
setwd("/mnt/campus/math/research/kfouda/main/HEC/Youssef/HEC_MAO_COOP")
```


```{r include=TRUE, message=FALSE, warning=FALSE}
source("./code_files/import_lib.R")
#path_to_data = "./Mao/saved_data/"
library(data.table)
```

### Model Summary

```{r}
Models <- c("Mao", "SoftImpute_Orig", "SoftImpute_Cov", "SoftImpute_L2",
            "SoftImpute_KFold", "SoftImpute_splr", "SoftImpute_splr_Kfold")

Note <- c("Mao's original model", "Original Soft-Impute from the library",
          "Soft-Impute with Covariates", "Soft-Impute with covariates and ridge",
          "Same as above but with K-fold", "Same as SoftImpute_L2 but with the Sparse-plus-low-rank representation", "Same as above but with K-fold")


include_cov <- rep("Yes",7)
include_cov[2] <- "No"
Cross_validation_type <- rep("Validation Set",7)
Cross_validation_type[c(1)] <- "K-fold (5)"
Cross_validation_type[c(5)] <- "K-fold (3)"
Cross_validation_type[c(7)] <- "K-fold (10)"
Regular_cov <- rep("Ridge", 7)
Regular_cov[2:3] <- "None"
Regular_cov[6:7] <- "Dimension Reduction"
New_Model <- rep("Yes",7)
New_Model[1:2] <- "No"

data.frame(Model=Models, Note=Note, `Has Covariates?`=include_cov,
           `Cross-Validation Type`=Cross_validation_type, 
           `Regularization on the Covariates?`=Regular_cov,
           `New Model`=New_Model) %>%
   kable("html", escape=FALSE, align = 'c', caption="Model Summary Table") %>%
     kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "center")

```



```{r}

combine_rmse_sd <- function(rmse_val, rmse_sd) {
   rmse_val = replace_na(as.character(rmse_val), '')
   rmse_sd = replace_na(as.character(rmse_sd), '')
   combined = paste0(rmse_val, " (", rmse_sd, ")")
   combined = ifelse(combined == ' ()', "", combined)
   combined
}
file_list <- list.files(
   path = path_to_data,
   pattern =
      "Replicate_Mao_Simulation_200_3_.*\\.csv$",
   full.names = TRUE,
   recursive = F
)

results = data.frame()
for (f in file_list)
   results = rbind(results, read.csv(f))

models <-
   c(
      "Mao",
      "SoftImpute (Original/ALS)",
      "SoftImpute with Covariates (No-L2/ALS)",
      "SoftImpute (SPLR)"
   )

dimensions = rep(paste0("n1=n2=",seq(400,800,200)),each=4)
dimensions[ ((1:12)%%4)!=1] = ''

results %<>%
   mutate_all(round, digits = 3) %>%
   transmute(
      #Dimension = dimensions,
      Model = rep(models, 3),
      RMSE_beta = combine_rmse_sd(error_beta_mean, error_beta_sd),
      RMSE_B = combine_rmse_sd(error_B_mean, error_B_sd),
      RMSE_A = combine_rmse_sd(error_A_mean, error_A_sd),
      Test_error = combine_rmse_sd(error_test_mean, error_test_sd),
      Rank = combine_rmse_sd(rank_mean, rank_sd),
      Time = combine_rmse_sd(time_mean, time_sd)
   )

```

```{r}

kable(
   results,
   format = "html",
   caption = "Table 1. Empirical root mean square errors (RMSEs),
      test errors (normalize RMSE as defined by Mao), estimated ranks, computational time,
   and standard errors; under model A = X beta + B and the logistic missing-at-random (MAR)
   model, with n1=n2=400,600,800,1000, number of covariates is 20 and rank of B is 10."
) %>%
   kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
   pack_rows("400x400", 1, 4) %>%
   pack_rows("600x600", (4 * 1) + 1, 4 * 2) %>%
   pack_rows("800x800", (4 * 2) + 1, 4 * 3) %>%
   column_spec(5,
               bold = T,
               background = grDevices::adjustcolor("turquoise", alpha.f = 0.01))

```

